site_name: Signum
site_url: https://a-sit-plus.github.io/signum/

theme:
  name: material
  logo: assets/signum-light-large.png
  favicon: assets/schloss.svg
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      font:
        text: Roboto

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: asp
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      font:
        text: Roboto

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: asp-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      font:
        text: Roboto


extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/a-sit-plus/signum
repo_name: a-sit-plus/signum

copyright: Copyright &copy; 2024 A-SIT Plus GmbH

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<opensource@a-sit.at>

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - Overview:
      - Home: index.md
      - CHANGELOG.md
      - Modules:
          - indispensable.md
          - indispensable-josef.md
          - indispensable-cosef.md
          - supreme.md
      - Examples:
          - index.md
  - API Docs: Foo.html