name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build jar
        run: ./gradlew assemble
      - name: Upload jar datatypes
        uses: actions/upload-artifact@v3
        with:
          name: datatypes
          path: |
            datatypes/build/libs/*jar
      - name: Upload jar datatypes-jws
        uses: actions/upload-artifact@v3
        with:
          name: datatypes-jws
          path: |
            datatypes-jws/build/libs/*jar
